<b>Scalaire</b>

l'utilisation de Numpy dans les exemples operation Math scalaires est inutile.

In [2]:
# Version Sans Numpy 

x=1
y=2
z=x+y

z

3

Pour utiliser numpy, 
installer avec : pip install numpy

Utilisation : il faut importer numpy dans 

In [4]:
import numpy as np

In [5]:
x=np.array(1)
y=np.array(2)
z=x+y
z

3

<b>Vecteur</b>


l'utilisation de Numpy dans les exemples operation Math vecteurs,permet de réaliser des resultats mathematiques

In [6]:
# Sans Numpy

x=[1,2]
y=[1,1]
z=x+y

z
# le resultat attendue : [2,3] OR
# Python natif réalise une opperation de concatination[1, 2, 1, 1] 

[1, 2, 1, 1]

In [7]:
# avec Numpy

x=np.array([1,2])
y=np.array([1,1])
z=x+y

z

# le resultat Obtenue : [2,3]

array([2, 3])

In [21]:
# nombre de dimension colone/Ligne
x.ndim

2

In [22]:
# calcul nombre d'elements
x.shape

(2, 2)

In [23]:
#montre le type d'objet stocké dans la memoire
x.dtype

dtype('int32')

<b>Matrice</b>
Decouverte de l'utilisation des matrices dans 'Numpy'

In [8]:
# Sans Numpy

x=[[1,2],[3,4]]
y=[[1,1],[1,1]]
z=x+y

z
# le resultat attendue : [2,3],[4,5] OR
# Python natif réalise une opperation de concatination [[1, 2], [3, 4], [1, 1], [1, 1]] 

[[1, 2], [3, 4], [1, 1], [1, 1]]

In [14]:
# avec Numpy

x=np.array([[1,2],[3,4]])
y=np.array([[1,1],[1,1]])
z=x+y

z

# le resultat Obtenue : [2,3],[4,5]

array([[2, 3],
       [4, 5]])

<b> Operation entre Matrice et Scalaire </b>


In [19]:
x1=np.array([1,2])
x2=np.array([3,4])
#operation math
x1-x2
x1*x2
#Test des op logique

array([3, 8])